plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	maven {
		name = "GitHubPackages"
		url = uri("https://maven.pkg.github.com/runtoolkit/dataLib")
		credentials {
			username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
			password = project.findProperty("gpr.key")  ?: System.getenv("GITHUB_TOKEN")
		}
	}
}

configurations {
	nested
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"datalib-fabricmod" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	nested("runtoolkit.datalib:datalib-core:5.1.2")    { transitive = false }
	nested("runtoolkit.datalib:datalib-log:5.1.2")     { transitive = false }
	nested("runtoolkit.datalib:datalib-command:5.1.2") { transitive = false }

	modImplementation("runtoolkit.datalib:datalib-core:5.1.2")    { transitive = false }
	modImplementation("runtoolkit.datalib:datalib-log:5.1.2")     { transitive = false }
	modImplementation("runtoolkit.datalib:datalib-command:5.1.2") { transitive = false }
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName" }
	}

	from(configurations.nested) {
		into "META-INF/jars/"
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}
}