# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.17.0
# Not: Fabric API surumunu build oncesi https://fabricmc.net/develop/ adresinden dogrula
fabric_version=0.137.0+26.2

# Mod Properties
mod_version=1.0.0
maven_group=com.runtoolkit
archives_base_name=rtwpanel
