from config import namespace, author, datapack_scoreboard, line_colour
from utils import make_file, make_dir

# Creates a blank datapack, with template advancements
def create_blank():
    # Data pack format 101.1 = release 26.1.2 (the stable "1.21.11"-line release that
    # precedes the 26.2 snapshot series). 26.2 snapshots keep bumping this number as
    # they progress (101.2 -> 102.0 -> ... -> 106.0 as of Snapshot 8), so there is no
    # single fixed 26.2 format yet. Use min/max range covering 26.1.2 through the
    # latest 26.2 snapshot tested (106) for broad compatibility; narrow this to your
    # exact snapshot's format if you need strict validation.
    make_file("pack.mcmeta", '{ \n\t"pack": {\n\t\t"pack_format": 101,\n\t\t"min_format": 101,\n\t\t"max_format": 106,\n\t\t"description": "Datapack generated with ericthelemur''s config generator"\n\t}\n}')

    # Folder names are singular since 1.21 ("function" not "functions").
    make_dir("data/minecraft/tags/function")
    make_file("data/minecraft/tags/function/load.json", '{\n\t"values": [\n\t\t"%s:load"\n\t]\n}' % namespace)
    make_file("data/minecraft/tags/function/tick.json", '{\n\t"values": [\n\t\t"%s:tick"\n\t]\n}' % namespace)

    make_dir("data/global/advancement")
    make_file("data/global/advancement/root.json", '{\n\t"display": {\n\t\t"title": "Installed Datapacks",\n\t\t"description": "",\n\t\t"icon": {\n\t\t\t"id": "minecraft:knowledge_book"\n\t\t},\n\t\t"background": "minecraft:textures/block/gray_concrete.png",\n\t\t"show_toast": false,\n\t\t"announce_to_chat": false\n\t},\n\t"criteria": {\n\t\t"trigger": {\n\t\t\t"trigger": "minecraft:tick"\n\t\t}\n\t}\n}')
    make_file("data/global/advancement/%s.json" % author, '{\n\t"display": {\n\t\t"title": "%(author)s",\n\t\t"description": "",\n\t\t"icon": {\n\t\t\t"id": "minecraft:player_head",\n\t\t\t"components": {\n\t\t\t\t"minecraft:profile": {\n\t\t\t\t\t"name": "%(author)s"\n\t\t\t\t}\n\t\t\t}\n\t\t},\n\t\t"show_toast": false,\n\t\t"announce_to_chat": false\n\t},\n\n\t"parent": "global:root",\n\t"criteria": {\n\t\t"trigger": {\n\t\t\t"trigger": "minecraft:tick"\n\t\t}\n\t}\n}' % {"author": author})

    make_dir("data/%s/advancement" % namespace)
    make_file("data/%s/advancement/%s.json" % (namespace, namespace), '{\n\t"display": {\n\t\t"title": "Generated Datapack",\n\t\t"description": "Datapack generated by ericthelemur''s datapack config generator.",\n\t\t"icon": {\n\t\t\t"id": "minecraft:white_dye"\n\t\t},\n\t\t"announce_to_chat": false,\n\t\t"show_toast": false\n\t},\n\t"parent": "global:%s",\n\t"criteria": {\n\t\t"trigger": {\n\t\t\t"trigger": "minecraft:tick"\n\t\t}\n\t}\n}' % author)

    make_dir("data/%s/function" % namespace)
    make_file("data/%s/function/load.mcfunction" % namespace, "execute if score %s = #zero constants run function %s:config/load_config" % (datapack_scoreboard, namespace))
    make_file("data/%s/function/tick.mcfunction" % namespace, "")
    make_file("data/%s/function/uninstall.mcfunction" % namespace, """function %(namespace)s:config/uninstall_config\nscoreboard players reset %(dp_sb)s\n\ntellraw @s {"text":"\\n                                                                                ","color":"%(line_colour)s","strikethrough":true}\ntellraw @s "Datapack uninstalled. Remove from datapacks folder before next restart or reload."\ntellraw @s {"text":"                                                                                ","color":"%(line_colour)s","strikethrough":true}""" % {"namespace": namespace, "line_colour": line_colour, "dp_sb": datapack_scoreboard})


    print("""
Template datapack created.
You now need to replace the placeholders in these files:
\tpack.mcmeta
\tdata/%s/advancement/%s.json
\t
""" % (namespace, namespace))